### ISSUE TITLE
Version 1.9.0 on modded 1.20.1 fails to load. Reverting to 1.8.3 resolves issue.

### ISSUE THREAD

**Issue by amyfromearth** [Steveplays28/realisticsleep#52]
I updated my mods and Minecraft wouldn't load. After checking the crash report I reverted to 1.8.3 and was able to launch game and play as before. 

[crash-2023-10-15_14.54.29-client.txt](https://github.com/Steveplays28/realisticsleep/files/12910791/crash-2023-10-15_14.54.29-client.txt)

Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [#realisticsleep:realisticsleep.mixins.json:WorldRendererMixin from mod realisticsleep] from phase [DEFAULT] in config [#realisticsleep:realisticsleep.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 20 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @ModifyConstant annotation on modifyCloudSpeed could not find any targets matching 'Lnet/minecraft/class_761;renderClouds(Lnet/minecraft/class_4587;Lnet/minecraft/util/math/Matrix4f;FDDD)V' in net.minecraft.class_761. Using refmap realisticsleep-refmap.json [PREINJECT Applicator Phase -> #realisticsleep:realisticsleep.mixins.json:WorldRendererMixin from mod realisticsleep -> Prepare Injections ->  -> constant$fhi000$realisticsleep$modifyCloudSpeed(F)F -> Parse]

**Comment by Steveplays28** [comment]
Weird, this worked in my development environment but doesn't work in release Minecraft.
Thanks for the report, I'll release a new version with a fix!

**Comment by Steveplays28** [comment]
This issue has been fixed in [`v1.9.1`](https://github.com/Steveplays28/realisticsleep/releases/latest).

**Comment by amyfromearth** [comment]
Awesome! That fixed it. You're quick!! <3
