### ISSUE TITLE
Message on only server-side

### ISSUE THREAD

**Issue by Sideways-Sky** [Steveplays28/realisticsleep#53]
Quilt 1.20.1

The mod is only installed on the server. I tried changing the config to remove the message, but it crashed the game.

![2023-10-21_17 41 20](https://github.com/Steveplays28/realisticsleep/assets/96632645/d7aa7a25-7343-4eec-a0d3-e3d8912339fa)

Thanks in advance!

**Comment by Steveplays28** [comment]
Hi Sideways-Sky, looks like the translation didn't get applied properly.
What version of Realistic Sleep are you using?

**Comment by Sideways-Sky** [comment]
I'm using 1.9.1

**Comment by Steveplays28** [comment]
Alright, thank you. I'll look into it!

**Comment by Sideways-Sky** [comment]
Thanks! And also thank you for being so fast! Wasn't expecting that ;)

**Comment by Steveplays28** [comment]
I can't reproduce this issue on Realistic Sleep `v1.9.1` and `1.20.1` Fabric, nor Quilt.
![image](https://github.com/Steveplays28/realisticsleep/assets/62797992/d8632665-c024-4d06-b96c-18ba0598cf3a)

**Comment by Sideways-Sky** [comment]
of course.

`{
  "sendDawnMessage": true,
  "dawnMessage": "The sun rises.",
  "sendDuskMessage": true,
  "duskMessage": "The night begins.",
  "sendSleepingMessage": true,
  "showTimeUntilDawn": true,
  "showTimeUntilDusk": true,
  "sendNotEnoughPlayersSleepingMessage": true,
  "allowDaySleeping": false,
  "sleepSpeedCurve": "LINEAR",
  "sleepSpeedMultiplier": 25.0,
  "blockEntityTickSpeedMultiplier": 25.0,
  "chunkTickSpeedMultiplier": 1.0,
  "raidTickSpeedMultiplier": 25.0,
  "fluidScheduledTickSpeedMultiplier": 25.0,
  "thunderTickSpeedMultiplier": 25.0,
  "iceAndSnowTickSpeedMultiplier": 25.0,
  "cropGrowthTickSpeedMultiplier": 25.0,
  "precipitationTickSpeedMultiplier": 25.0,
  "blockRandomTickSpeedMultiplier": 1.0,
  "fluidRandomTickSpeedMultiplier": 1.0,
  "cloudSpeedMultiplier": 25.0,
  "tickDelay": -1
}`

**Comment by Steveplays28** [comment]
Do you have Realistic Sleep installed only serverside? Maybe that's the issue, would be an unintended bug.

**Comment by Sideways-Sky** [comment]
Thanks!

**Comment by salocinyeet** [comment]
I am getting the same message for Fabric 1.20.1 using version 1.9.1. When sleep the message doesn't translate but we do see "The Sun Rises"
![2023-11-03_11 33 29](https://github.com/Steveplays28/realisticsleep/assets/32781165/0ce56143-d40b-4bd1-89e4-c72d73a0d0b6)
![2023-11-03_11 37 12](https://github.com/Steveplays28/realisticsleep/assets/32781165/8f855f1f-0ffa-4885-9cea-3483d51a1128)

**Comment by salocinyeet** [comment]
We have downgraded to version 1.8.2 and it seems to work in this version.
![2023-11-03_11 42 12](https://github.com/Steveplays28/realisticsleep/assets/32781165/ca891727-b00a-4421-a08e-a33d07379a30)

**Comment by iloominaty** [comment]
![bilde](https://github.com/Steveplays28/realisticsleep/assets/43035621/c009ccb8-a254-46bb-a652-a09b2446998d)
![bilde](https://github.com/Steveplays28/realisticsleep/assets/43035621/d9b57351-ad55-4fcb-a2b0-98650420f8e1)
![bilde](https://github.com/Steveplays28/realisticsleep/assets/43035621/3c2bf904-4834-48c8-ab69-21dcb28a20bf)

I am also experiencing this issue.
Here is what is installed on the server and client.

**Comment by Deerhall** [comment]
I have the same variable text when sleeping. Running mod server only (it's declared as **Server**, not **Client and Server**). Differance is I run the mod on Fabric 1.20.2 (fabric-server-mc.1.20.2-loader.0.14.24-launcher.0.11.2).

If I set "  `sendSleepingMessage": false,`

The client is disconnected with this error:
Internal Exception: io.netty.handler.codec.DecoderException: Received unexpected null component

Server spits out:
`[19:27:29] [Netty Server IO #1/WARN]: An exception was thrown by net.minecraft.class_2535$$Lambda/0x000002512f189738.operationComplete()
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2561.method_10858(int)" because "$$0" is null
        at net.minecraft.class_3222.method_43507(class_3222.java:1374) ~[server-intermediary.jar:?]
        at net.minecraft.class_7648$2.method_45086(class_7648.java:30) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_45082(class_2535.java:327) ~[server-intermediary.jar:?]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590) ~[netty-common-4.1.97.Final.jar:?]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557) ~[netty-common-4.1.97.Final.jar:?]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492) ~[netty-common-4.1.97.Final.jar:?]
        at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:185) ~[netty-common-4.1.97.Final.jar:?]
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30) ~[netty-transport-4.1.97.Final.jar:?]
        at net.minecraft.class_2535.method_36942(class_2535.java:323) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_52917(class_2535.java:316) ~[server-intermediary.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]`

**Comment by Steveplays28** [comment]
Hi all, haven't looked into this issue yet lately. Does the issue persist when you install the mod clientside as well? I'm currently assuming that's the issue.

**Comment by IonicEcko** [comment]
Yep with the mod installed client side as well it works.

**Comment by Steveplays28** [comment]
I'll see if I can work out a fix, it's an unintended bug.

**Comment by Steveplays28** [comment]
I've integrated the [Server Translation API](https://github.com/NucleoidMC/Server-Translations), so serverside translations work now, from `v1.9.2` and up!
You can change the language from the client, and it should sync with the server.

Also, the API is included into Realistic Sleep's jar as a JiJ dependency, so no need to download it manually.
